### ISSUE TITLE
Unrecognized option "jku" under "jose.keys.test". Did you mean "jwk"?

### ISSUE THREAD

**Issue by marijnhurkens** [web-token/jwt-framework#164]
**Describe the bug**
When using the config for using a JKU key set I get an error that JKU is not a supported option.

**To Reproduce**

In httplu.yaml
```
httplug:
    plugins:
        cache:
            cache_pool: 'cache.app'
            config:
                default_ttl: 1800
    clients:
        jwk:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.cache']
```

In jose.yaml
```
jose:
    jku_factory:
        enabled: true
        client: 'httplug.client.jwk'
        request_factory: 'httplug.message_factory'
    keys:
        test:
            jku: # method
                url: '%env(TOEGANG_BASE_URI)%/oauth/certs'
```

Error:
```
(1/1) InvalidConfigurationExceptionUnrecognized option "jku" under "jose.keys.test". Did you mean "jwk"?
```

Installed package is the latest `composer require web-token/jwt-framework` (1.3.1).

**Expected behavior**
For the configuration to work.

**Desktop (please complete the following information):**
PHP 7.1, symfony 4.2

Thanks :)
