### ISSUE TITLE
Loading JWK from P12 file or add custom JWKSource

### ISSUE THREAD

**Issue by unixslayer** [web-token/jwt-framework#207]
In Symfony application I tried to load JWK from P12 file with following configuration:

```
jose:
  keys:
    sig:
      file:
        path: '%env(resolve:JOSE_SIG_PATH)%'
        password: '%env(JOSE_SIG_SECRET)%'
```

On runtime I got an error "**Unable to load the key.**". This is because file source uses `\Jose\Component\KeyManagement\JWKFactory::createFromKeyFile`. When using `\Jose\Component\KeyManagement\JWKFactory::createFromPKCS12CertificateFile` method, file is loaded correctly. 

Tried to define my own source as implementation of `\Jose\Bundle\JoseFramework\DependencyInjection\Source\KeyManagement\JWKSource\JWKSource`, tagging it with `jose.jwk_source` tag and use it like this:

```
jose:
  keys:
    sig:
      p12:  # p12 is the key returned from my implementation
        path: '%env(resolve:JOSE_SIG_PATH)%'
        password: '%env(JOSE_SIG_SECRET)%'
```
but now I have following error: "**Unrecognized option "p12" under "jose.keys.sig". Available options are "certificate", "file", "jwk", "jwkset", "secret", "values", "x5c".**"

Cache was cleared.

I want this to be done with "zero application code" solution. How can I add and then use my own JWKSource? Or can separated p12 source be added?
