### ISSUE TITLE
Using index with kid gives error

### ISSUE THREAD

**Issue by bogdaniel** [web-token/jwt-framework#255]
I have a set of keys generated for the lexik jose bridge bundle that I would to use in another app that implements only jwt-framework library but I discovered that if I set the index key as a string I'm not allowed. Is there any way to load those keys using jwt-framework? Seems that from the configuration the support is limited only to integer types.
If I used kid in my keys I will get that the index should be only integer and if I set it to 0 I will get an error that it can't find the keys.

Sample config:

```
jose:
  keys:
    signature_keyset:
      jwkset: # Method
        key_set: 'jose.key_set.signature_keyset' # JWKSet service
#        index: "Y3m_Kg_nlovRJuZtIOCTPchBM9jUDTzWZn6tTvcEdGY" # Use key at index 0
        index: 0  # Use key at index 0
        is_public: true
    encryption_keyset:
      jwkset: # Method
        key_set: 'jose.key_set.encryption_keyset' # JWKSet service
#        index: "DnekdHbanVJh6yZOvBFKpszOJQIAVsHRytAZfXjsCMk" # Use key at index 0
        index: 0  # Use key at index 0
        is_public: true

  key_sets:
    signature_keyset: # The key set we want to share
      jwkset:
        value: "%env(resolve:SL_JOSE_BRIDGE_SIGNATURE_KEYSET)%"
        is_public: true
    encryption_keyset: # The key set we want to share
      jwkset:
        value: "%env(resolve:SL_JOSE_BRIDGE_SIGNATURE_KEYSET)%"
        is_public: true
  jwk_uris:
    signature_keyset:
      id: 'jose.key_set.signature_keyset' # The key set service to share
      path: '/signature' # Path of the key set. Final path is hostname/route_prefix/path: https://www.foo.com/keys/certs
    encryption_keyset:
      id: 'jose.key_set.encryption_keyset' # The key set service to share
      path: '/encryption' # Path of the key set. Final path is hostname/route_prefix/path: https://www.foo.com/keys/certs
```
