### ISSUE TITLE
UrlKeySetFactory implementation with Httplug, Nyholm, Symfony http client

### ISSUE THREAD

**Issue by cacahouwete** [web-token/jwt-framework#259]
**Describe the bug**
I just installed httplug with symfony http client and Nyholm to try to use Key Set Management From A X5U (X509 Certificates Url).
evrythings works fine until I put 

```
jose:
    key_sets:
        key_name:
            x5u: # Method
                url: 'https://www.googleapis.com/oauth2/v1/certs'
```
I have to following error:
```
Argument 2 passed to Jose\Component\KeyManagement\UrlKeySetFactory::__construct() must implement interface Psr\Http\Message\RequestFactoryInterface, instance of Nyholm\Psr7\Factory\HttplugFactory given, called in /app/var/cache/dev/ContainerMlkkVie/srcApp_KernelDevDebugContainer.php on line 824
```

**To Reproduce**
1. Install in a symfony(^4.4) project :
```
        "php-http/httplug-bundle": "^1.18",
        "php-http/cache-plugin": "^1.7",
        "nyholm/psr7" :"^1.0",
        "symfony/http-client": "^4.4",
        "web-token/jwt-bundle": "^2.1",
        "web-token/jwt-key-mgmt": "^2.1"
```
2. Use following basic configuration for httplug:
```
httplug: # Example of client configuration
  plugins:
    cache: # We use the cache plugin
      cache_pool: 'cache.app' # We use the PSR-6 Cache service of the application
      config:
        default_ttl: 1800 # TTL set to 30 min
  clients:
    acme:
      factory: 'httplug.factory.symfony'
      plugins: ['httplug.plugin.cache'] # We enable the cache plugin for that client.
```
3. Jose config:
```
jose:
  jku_factory:
    enabled: true
    client: 'httplug.client.acme' # The Httplug client
    request_factory: 'httplug.message_factory'

  key_sets:
    main_key:
      x5u: # Method
        url: 'https://www.googleapis.com/oauth2/v1/certs'

```
4. Nyholm config if not auto confi by flex:
```
services:
    # Register nyholm/psr7 services for autowiring with PSR-17 (HTTP factories)
    Psr\Http\Message\RequestFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\ResponseFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\ServerRequestFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\StreamFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\UploadedFileFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\UriFactoryInterface: '@nyholm.psr7.psr17_factory'

    # Register nyholm/psr7 services for autowiring with HTTPlug factories
    Http\Message\MessageFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\RequestFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\ResponseFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\StreamFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\UriFactory: '@nyholm.psr7.httplug_factory'

    nyholm.psr7.psr17_factory:
        class: Nyholm\Psr7\Factory\Psr17Factory

    nyholm.psr7.httplug_factory:
        class: Nyholm\Psr7\Factory\HttplugFactory
```

**Expected behavior**
I expect to not have an error when I follow what the documentation say.

**Screenshots**
![image](https://user-images.githubusercontent.com/1099956/82826864-33df6d00-9eae-11ea-8f6d-a82dd066cb34.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome(v84)

**Additional context**
I don't know if it's a real bug or if it's a missconfig.

**Comment by Spomky** [comment]
Your PSR-7 request factory service seems to be `Psr\Http\Message\RequestFactoryInterface`, not 'httplug.message_factory'.

The following configuration should work fine:

```yaml
jose:
  jku_factory:
    enabled: true
    client: 'httplug.client.acme' # The Httplug client
    request_factory: 'Psr\Http\Message\RequestFactoryInterface'

  key_sets:
    main_key:
      x5u: # Method
        url: 'https://www.googleapis.com/oauth2/v1/certs'
```
