### ISSUE TITLE
Algorithm should be autoloaded when using web-token/jwt-bundle 

### ISSUE THREAD

**Issue by VincentLanglet** [web-token/jwt-framework#265]
I'm certainly missing something.

But when I try the doc https://web-token.spomky-labs.com/the-symfony-bundle/signed-tokens/jws-creation#jws-builder-factory-service with `RS256`, I get 
```
The algorithm with the alias "RS256" is not supported.
```

I installed `web-token/jwt-bundle` and `web-token/jwt-signature-algorithm-rsa`, but seems like there is something more to do... Is there some config to add in order to defined supported algorithms ?

**Comment by VincentLanglet** [comment]
I had to add 
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\Signature\Algorithm\RS256:
        tags:
            - name: jose.algorithm
              alias: RS256
```

Shouldn't the default algorithm loaded by default ?

**Comment by Spomky** [comment]
Hi @VincentLanglet,

Thank you for this bug report. I think I have found the error.
Can you tell me if the GMP extension is available on your platform ? If not, I guess this this is the reason why the algorithm is not correctly loaded.
I will that ASAP. 

Regards.

**Comment by VincentLanglet** [comment]
> Can you tell me if the GMP extension is available on your platform ? If not, I guess this this is the reason why the algorithm is not correctly loaded.

Yes I have the gmp extension.

But I still had to add all the algorithm I used in my code in the config.
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\Signature\Algorithm\RS256:
        tags:
            - name: jose.algorithm
              alias: RS256

    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CBCHS256:
        tags:
            - name: jose.algorithm
              alias: A128CBC-HS256

    Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP256:
        tags:
            - name: jose.algorithm
              alias: RSA-OAEP-256
```
