### ISSUE TITLE
Create a JWKSet with existing JWK with the symfony bundle

### ISSUE THREAD

**Issue by tomme87** [web-token/jwt-framework#361]
**Description**
Looks like there is no way to create a JWKSet with existing JWK defined with the Symfony bundle.

I would like to be able to create a key_set from other keys I have defined in the config.

**Example**
```yaml
jose:
  keys:
    key1:
      file:
        path: '/path/to/key1'
    key2:
      file:
        path: '/path/to/key2'

  key_sets:
    keyset_name:
      jwks: # This is the method I want to add
        - key1
        - key2
```
