### ISSUE TITLE
Call to a member function list() on null at web-token/jwt-bundle/DataCollector/JWECollector.php line 172

### ISSUE THREAD

**Issue by PeterMead** [web-token/jwt-framework#595]
### Version(s) affected

3.4.6

### Description

When using a JWE Builder with no compression as a Symfony service the debugging collector will error because `getCompressionMethodManager` returns `null`.

### How to reproduce

```yaml
jose:
    jwe:
        builders:
            builder1:
                key_encryption_algorithms: ['A256GCMKW']
                content_encryption_algorithms: ['A256CBC-HS512']
                #compression_methods: ['DEF']
                is_public: true
```

```php
$jweBuilder = $container->get('jose.jwe_builder.builder1');

$jweBuilder->create()
    ->build();

```
