### ISSUE TITLE
Allow services to have custom tags

### ISSUE THREAD

**Issue by Spomky** [web-token/jwt-framework#66]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| BC Break report?     | no
| RFC? / Specification | no
| Version              | 1.x

The bundle creates numerous new services for keys, key sets, JWS Builders and so on.
Services can be retrieved using their ID (e.g. `jose.key.xxxxxx`).
Applications may need to tag those services to perform additional tasks e.g. to list them all or to manipulate them using a compiler pass.

It could be great to add the possibility to define custom tags directly using the bundle configuration and using the Configuration Helper.

Example:

```yaml
jose:
    checkers:
        claims:
            checker1:
                claims: ['exp', 'iat', 'nbf', 'custom_checker']
                is_public: true
                tags:
                    my_app.security.claim_checker: {alias: 'security_check'}
```
